#!/bin/bash

while true; do
  mixtape=`ia search collection:hiphopmixtapes -i | sort -R | head -n 1`
  playlist="http://archive.org/download/${mixtape}/${mixtape}_vbr.m3u"
  mplayer -msgcolor -msglevel all=0:demux=4:statusline=5 -playlist $playlist 2>/dev/null
done

exit 0
